ALTER TABLE analysis_report
    ADD COLUMN include_weather TINYINT(1) DEFAULT NULL COMMENT '是否包含天气上下文',
    ADD COLUMN include_prediction TINYINT(1) DEFAULT NULL COMMENT '是否包含预测上下文',
    ADD COLUMN model_name VARCHAR(128) DEFAULT NULL COMMENT 'LLM模型名称',
    ADD COLUMN prompt_snapshot LONGTEXT DEFAULT NULL COMMENT 'Prompt快照',
    ADD COLUMN context_snapshot LONGTEXT DEFAULT NULL COMMENT '上下文快照',
    ADD COLUMN raw_response LONGTEXT DEFAULT NULL COMMENT '模型原始响应',
    ADD COLUMN risk_level VARCHAR(32) DEFAULT NULL COMMENT '风险等级',
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '状态：PENDING，SUCCESS，FAILED',
    ADD COLUMN error_message TEXT DEFAULT NULL COMMENT '错误信息',
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    ADD KEY idx_report_status (status);
