-- 新闻来源与公开分类增量迁移。可重复执行，不删除或重建既有数据。
DELIMITER $$
DROP PROCEDURE IF EXISTS migrate_news_sources$$
CREATE PROCEDURE migrate_news_sources()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='category') THEN ALTER TABLE news ADD COLUMN category VARCHAR(32) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='content_type') THEN ALTER TABLE news ADD COLUMN content_type VARCHAR(32) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='source_type') THEN ALTER TABLE news ADD COLUMN source_type VARCHAR(32) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='source_name') THEN ALTER TABLE news ADD COLUMN source_name VARCHAR(128) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='source_url') THEN ALTER TABLE news ADD COLUMN source_url VARCHAR(1000) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='external_id') THEN ALTER TABLE news ADD COLUMN external_id VARCHAR(255) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='source_published_at') THEN ALTER TABLE news ADD COLUMN source_published_at DATETIME DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='fetched_at') THEN ALTER TABLE news ADD COLUMN fetched_at DATETIME DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='external_content') THEN ALTER TABLE news ADD COLUMN external_content TINYINT NOT NULL DEFAULT 0; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='warning_level') THEN ALTER TABLE news ADD COLUMN warning_level VARCHAR(64) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='warning_region') THEN ALTER TABLE news ADD COLUMN warning_region VARCHAR(255) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='warning_agency') THEN ALTER TABLE news ADD COLUMN warning_agency VARCHAR(255) DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='effective_at') THEN ALTER TABLE news ADD COLUMN effective_at DATETIME DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND COLUMN_NAME='expires_at') THEN ALTER TABLE news ADD COLUMN expires_at DATETIME DEFAULT NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND INDEX_NAME='idx_news_category_publish') THEN ALTER TABLE news ADD INDEX idx_news_category_publish(category,status,published_at); END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='news' AND INDEX_NAME='uk_news_external') THEN ALTER TABLE news ADD UNIQUE INDEX uk_news_external(source_type,external_id); END IF;
END$$
CALL migrate_news_sources()$$
DROP PROCEDURE migrate_news_sources$$
DELIMITER ;

UPDATE news SET category=CASE WHEN news_type='INDUSTRY_NEWS' THEN 'INDUSTRY' ELSE 'PLATFORM' END WHERE category IS NULL;
UPDATE news SET content_type=CASE WHEN news_type='NOTICE' THEN 'PLATFORM_NOTICE' ELSE 'PLATFORM_NEWS' END, source_type='PLATFORM', source_name='光伏智云平台' WHERE source_type IS NULL;
